// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginData struct {
	Token string `json:"token"`
	Error *int   `json:"error,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Sighting struct {
	ID            int    `json:"id"`
	TigerID       int    `json:"TigerId"`
	SeenAt        string `json:"SeenAt"`
	SeenAtLat     string `json:"SeenAtLat"`
	SeenAtLon     string `json:"SeenAtLon"`
	PhotoLocation string `json:"PhotoLocation"`
}

type TigerData struct {
	ID          int         `json:"id" gorm:"primary_key"`
	UserName    string      `json:"userName"`
	Name        string      `json:"name"`
	DateOfBirth string      `json:"dateOfBirth"`
	Sightings   []*Sighting `json:"Sightings"  gorm:"foreignKey:TigerID;references:ID"`
}

type UserData struct {
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

type UserDataWithPassword struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}
